### ISSUE TITLE
Rewrite basic_usage.Rmd for YAML support

### ISSUE THREAD

**Issue by kyleam** [metrumresearchgroup/mrgvalprep#25]
Quoting @seth127 from #24:

> After #23 we will begin to encourage users to keep stories/requirements in the repo with the code (and use `read_spec_yaml()`) instead of externally in a Googlesheet.

`vignettes/basic_usage.Rmd` should be rewritten to at least mention YAML alongside Google Sheets.  But, depending on how strongly we want to encourage YAML, perhaps the vignette should focus on YAML input and just mention support for Google Sheets.

**Comment by seth127** [comment]
I think what we want to do is move the two examples in https://metrumresearchgroup.github.io/mrgvalprep/articles/basic_usage.html to a new "legacy methods" vignette and then put the YAML front and center in "Basic Usage"
