### ISSUE TITLE
Convert full test names to Test ID's

### ISSUE THREAD

**Issue by seth127** [metrumresearchgroup/mrgvalprep#33]
The old format required you to have the full test names listed in your stories (instead of Test ID's). It would be awesome if we could have a separate function that parsed through those, auto-generated Test ID's, and then added those ID's to both the test code and the stories YAML. Might be a little brittle and fragile, but I bet we could handle a lot of the cases with some pretty simple string manipulation of the files. Even if it only got 80% of them, this would still save a lot of time. Especially if it gave you a clear report of which ones needed to be revisited manually.

**Comment by barrettk** [comment]
So in the example repo we're using, I found this [issue](https://github.com/metrumresearchgroup/mrgvalidatetestreference/issues/3):
![image](https://user-images.githubusercontent.com/18685116/160462638-5083aaf7-5f90-4c52-bdc7-3f625ec508fa.png)

However, the actual test file only has one test that matches this string:
![image](https://user-images.githubusercontent.com/18685116/160462808-7ee018e4-a532-42d8-b1b0-4c393ac6b15a.png)

The function cannot account for this error. In cases like this, I will force delete whatever is not replaced. We can discuss other solutions moving forward

**Comment by seth127** [comment]
generally, I'd say this fits into the broad category of "there are situations where this won't work and we'll have to fix it manually" which we know there will be some of and that's fine. I think the most important things are:

* We should return something that makes it easy for the user to see what didn't work and find where in their test suite (and stories) they need to fix it manually.
* Not sure if this ^ should just be a warning printed to the console, but I sort of think it would be better to return a tibble or something, similar to how [`mrgvalidate::find_missing`](https://github.com/metrumresearchgroup/mrgvalidate/blob/develop/R/input-checks.R#L28-L139) and friends work.
* Don't break stuff (i.e. if you can't add a work Test ID, probably don't touch that part of the code)
* I'm not sure what you mean by "I will force delete whatever is not replaced" in the previous comment, but I worry it's related to this bullet ^.

**Comment by barrettk** [comment]
PR https://github.com/metrumresearchgroup/mrgvalprep/pull/36 addresses this issue
