### ISSUE TITLE
assign_test_ids may overwrite text outside of of test_that context

### ISSUE THREAD

**Issue by barrettk** [metrumresearchgroup/mrgvalprep#41]
In this example, the tests were named "png" and "bmp". The devices were also replaced given that the text was identical:
![image](https://user-images.githubusercontent.com/18685116/163024704-0cda2727-7164-45c6-80da-316b790cd292.png)

In this circumstance, it also replaced the device in other test files:
![image](https://user-images.githubusercontent.com/18685116/163025208-b75ad623-5f9b-4faf-b73b-e9d341d53e2b.png)

Im not sure whether it makes sense to fix this "bug" or not. In my opinion I think we should opt to have more detailed test names, as this is a very specific circumstance that wouldn't arise often

**Comment by kyleam** [comment]
Fwiw in my opinion this is a legitimate bug/oversight that should be fixed.  I think you could pull out, rework (mostly like just adding more groups), and reuse the more specific regex from `parse_tests`:

https://github.com/metrumresearchgroup/mrgvalprep/blob/9054ddbb96ee34b7fbdb523b67dfbf77b46e5fbd/R/assign-test-ids.R#L132

**Comment by barrettk** [comment]
@kyleam what does 'Fwiw' stand for?
